spring:
  application:
    name: wallet
  datasource:
    url: jdbc:h2:mem:wallet;
    username: application_user
    password: here_is_a_password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update



